# Generated by Django 4.0 on 2021-12-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='name',
            new_name='pizza_name',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='name',
            new_name='topping_name',
        ),
    ]
