# Generated by Django 4.0 on 2021-12-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_rename_name_pizza_pizza_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'toppings'},
        ),
    ]
